### ISSUE TITLE
Puma 6.2.1 warns about threads started in app boot

### ISSUE THREAD

**Issue by victorfgs** [judoscale/judoscale-ruby#170]
Hi there,

Ever since the 5.x.x release, Puma detects and warns threads that are started in app boot (before the forking process) as you can see [here](https://github.com/puma/puma/issues/2421). I am currently seeing the judoscale gem as one of those threads in my app(I think the thread that reports web metrics are instantiated once in the Runner process when running in cluster mode?)

It seems to me that this thread should be marked as fork safe as it was [on rails connection pooling](https://github.com/rails/rails/pull/40399) since Puma should not be worried about it.

Is my analysis correct? Is there something that I can help to fix this warning?

**Comment by adamlogic** [comment]
I think you're right that we can mark the thread as fork-safe, since we'll detect if the PID changes and start a separate reporter thread for each fork.

https://github.com/judoscale/judoscale-ruby/blob/3c30f607405ca4e772e3f6fb3cb10bc94660bd4e/judoscale-ruby/lib/judoscale/reporter.rb#L66-L68

I swear we've had this discussion before, but I can't find any history of it. 🤔
