### ISSUE TITLE
Turn off `INFO -- : [Judoscale] Reporting 0 metrics` in a rake task output

### ISSUE THREAD

**Issue by ArturT** [judoscale/judoscale-ruby#219]
Is it possible to disable the following logs in the output of a rake task?

```
I, [2024-10-08T10:37:19.514254 #2]  INFO -- : [Judoscale] Reporting 0 metrics
I, [2024-10-08T10:37:22.400691 #2]  INFO -- : [Judoscale] Reporting 0 metrics
I, [2024-10-08T10:37:25.359942 #2]  INFO -- : [Judoscale] Reporting 0 metrics
```

Is there a reason why Judoscale is running when we run a rake task on Heroku? It's not a web or worker-related process, so I thought Judoscale should be off. Thanks.

---
judoscale-rails (1.8.0)

**Comment by adamlogic** [comment]
Hey @ArturT, we don't have a way to know if we're running in a web or worker process, but we do suppress the reporter [in certain rake tasks](https://github.com/judoscale/judoscale-ruby/blob/main/judoscale-rails/lib/judoscale/rails/railtie.rb#L41). We don't suppress in _all_ rake tasks since some job backends (DJ, Resque) use Rake as their executable for processing jobs.

We could possibly make that "blocklist" of rake tasks configurable. Would that resolve your issue?

**Comment by ArturT** [comment]
Yes, that would be helpful.
