### ISSUE TITLE
Can't change back to ms time range?

### ISSUE THREAD

**Issue by MGPalmer** [judoscale/judoscale-ruby#97]
Hello!

First: Love this service!

And: Not sure this is a bug but after having to turn our worker dynos to a 1s-10s range, I can't seem to find a way to go back down below 1s to enter a threshold in ms. Am I blind?

![image](https://user-images.githubusercontent.com/300129/205674543-5d2e9f4e-c038-439d-be8d-2a74f4055909.png)

Thanks!

**Comment by jon-sully** [comment]
Greetings @MGPalmer! 👋 

Thanks for the love ☺️

You're not blind! If you switch to whole seconds then we presume you _intend_ to stay within the scale of whole seconds. We find that it's rare to have _worker_ dynos scaling based on queue times under 1 second (must have QUICK queue requirements!). That said, we can totally switch you back to milliseconds for this dyno type 👍 could you send us an email with the URL from that particular screenshot? hello@judoscale.com

**Comment by adamlogic** [comment]
Thanks Martin!

You're not blind—this was a change in the recent redesign, but there is a workaround:

If you enter a decimal value and save, this field will change to "milliseconds" instead of "seconds".

<img width="1166" alt="CleanShot 2022-12-05 at 12 40 26@2x" src="https://user-images.githubusercontent.com/372/205705284-ee618118-a776-41a6-878c-cfd1cf19fe41.png">

<img width="1158" alt="CleanShot 2022-12-05 at 12 40 35@2x" src="https://user-images.githubusercontent.com/372/205705292-1f8f3e25-2804-4eb0-93eb-fa6bb0440c35.png">

Note that this is a workaround for an intentional change with worker dynos. When thinking about job queue time, the difference between 1 second and 100 milliseconds is almost no change in behavior. In either case, you're essentially downscaling only when there are no jobs queued at all.

So we changed the UI granularity to "seconds" to encourage thinking about job queue time as a more coarse-grained setting.

If you have a use case where it makes a tangible difference to set this below one second, I'd love to hear about it!

**Comment by adamlogic** [comment]
Dang, Jon beat me by seconds! Sorry to gang up on you. 😅 

And just to clarify, you're able to do this workaround on your own. No need to email us unless you have more info you'd like to share. 🙂

**Comment by MGPalmer** [comment]
@adamlogic @jon-sully Ah wow thanks for all the good advice! And dang it I could've sworn I tried the decimal entry and it didn't work. Now it does. Huh.
And thanks, it's good to know about the intentional second range, that actually makes a lot of sense. We just had it below for a long time and I wanted to revert and couldn't in the moment. I'll just leave it then :)
